### ISSUE TITLE
view 생성

### ISSUE THREAD

**Issue by memorial0** [likelion11-kangwon/NoneFile_FrontEnd#10]
## 구현할 기능
- loginview
- mainview

## Tasks
- [ ] 각 뷰어별 컴포넌트 합치기 = 페이지 만들기 총 4개의 페이지! 
- [ ] 로그인뷰에 있는 배경 svg 너비 자동 설정 
- [ ] main뷰에 post부분 레이아웃 설정

## 추가사항
- 프로필이 컴포터는가 깃허브에 없습니다. 프로필 컴포넌트 푸시해주세요 @chamjoeun0111
